#!/bin/bash

date
DPATH=/sibcb1/wuweilab1/wuwei-lab/ToLiangYu/WangLuLab_ChIP-seq/
Bowtie2index=/sibcb1/wuweilab1/wuwei-lab/Reference/Fly/dm6/Sequence/Bowtie2Index/genome
dm6Blacklist=/sibcb1/wuweilab1/liangyu/END-seq-analysis/WangLu/20221113/dm6-blacklist.v2.bed
dm6ChromSize=/sibcb1/wuweilab1/wuwei-lab/Reference/Fly/dm6/Sequence/dm6.chrom.sizes

cutadapt  -e 0.1 -O 3 -m 55 --quality-cutoff 25 -a CTGTCTCTTATA -A CTGTCTCTTATA -o fixed.fastq/${Filename}_cutadapt_1_fq.gz -p fixed.fastq/${Filename}_cutadapt_2_fq.gz  ${DPATH}${Filename}_1.fq.gz ${DPATH}${Filename}_2.fq.gz 
bowtie2 -x ${Bowtie2index} -1 fixed.fastq/${Filename}_cutadapt_1_fq.gz -2 fixed.fastq/${Filename}_cutadapt_2_fq.gz  -S bam.bowtie2/${Filename}.sam --no-unal
samtools view -h -b -f 3 -F 12 -q 20 -F 256 bam.bowtie2/${Filename}.sam   -@ 10 > bam.bowtie2/${Filename}.bam
samtools sort -@ 24 -o bam.bowtie2/${Filename}.sorted.bam bam.bowtie2/${Filename}.bam
rm bam.bowtie2/${Filename}.bam
samtools index bam.bowtie2/${Filename}.sorted.bam -@ 10
java -Xms20g -Xmx20g -XX:ParallelGCThreads=4 -jar /sibcb1/wuweilab1/liangyu/Software/picard/picard.jar MarkDuplicates I=bam.bowtie2/${Filename}.sorted.bam O=bam.bowtie2/${Filename}.sorted.rmdup.bam M=bam.bowtie2/${Filename}.sorted.rmdup.matrix ASO=coordinate REMOVE_DUPLICATES=true 2>bam.bowtie2/${Filename}.sorted.rmdup.log
bedtools bamtobed -i bam.bowtie2/${Filename}.sorted.rmdup.bam|bedtools intersect -v -a - -b ${dm6Blacklist} > bedfile/${Filename}.sorted.rmdup.bed
rpm=$(wc -l bedfile/${Filename}.sorted.rmdup.bed|cut -f 1 -d ' '|awk '{printf "%f\n",$1/1000000.0}')
rpm=$(awk '{printf "%f\n",1/("'$rpm'")}' /sibcb1/wuweilab1/wuwei2022/Wuwei/Pipeline/tst.txt)
bedtools genomecov -bg -scale $rpm -i bedfile/${Filename}.sorted.rmdup.bed -g ${dm6ChromSize}|bedtools sort -i stdin> bigwig/${Filename}.bedgraph
bedGraphToBigWig bigwig/${Filename}.bedgraph ${dm6ChromSize} bigwig/${Filename}.bw

rm bigwig/${Filename}.bedgraph
rm bam.bowtie2/${Filename}.sam
date

